name: GitOps CD Flow

on:
  push:
    branches:
      - main

jobs:
  sync-manifest:
    name: Sync GitOps Manifest on Production Server
    runs-on: self-hosted

    steps:
      - name: Deploy Locally on Self-Hosted
        run: |
          set -e
          cd /Users/hork/Downloads/GitOps-Manifest/
          git pull origin main
